name: Mobile Release Production

on:
  workflow_dispatch:

jobs:
  android:
    defaults:
      run:
        working-directory: packages/mobile
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Export version from package.json
        run:
          echo "PACKAGE_VERSION=$(grep '"version"' ../web/package.json | cut -d '"' -f 4 | cut -d "-" -f 1)" >> $GITHUB_ENV
      - name: Setup react-native kernel and increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      # - name: Decode Production Android keystore
      #   run: |
      #     echo "${{ secrets.ANDROID_KEYSTORE }}" > keystore.keystore.asc
      #     gpg -d --passphrase "${{ secrets.KEYSTORE_PASSPHRASE }}" --batch keystore.keystore.asc > android/app/keystore.keystore
      - name: Install dependencies
        run: yarn install --immutable
      - run: yarn build:mobile
      - name: Ruby Setup for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          working-directory: 'packages/mobile'
      - name: fastlane
        uses: maierj/fastlane-action@v1.4.0
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
          BUILD_NUMBER: ${{ github.run_number }}
          # ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          # ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          # ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          # GOOGLE_PLAY_JSON_KEY_DATA: ${{ secrets.GOOGLE_PLAY_JSON_KEY_DATA }}
        with:
          lane: 'android prod'
          subdirectory: 'packages/mobile'

      - name: Generate Release Notes
        uses: ./actions/release-notes
        with:
          package: mobile
        id: release-notes
        continue-on-error: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CI_PAT_TOKEN }}
          tag_name: "@standardnotes/mobile@${{ env.PACKAGE_VERSION }}"
          name: "Mobile ${{ env.PACKAGE_VERSION }}"
          body: ${{ steps.release-notes.outputs.result }}
          prerelease: true
          draft: false
          files: |
            packages/mobile/android/app/build/outputs/bundle/prodRelease/app-prod-release.aab
            packages/mobile/android/app/build/outputs/apk/prod/release/app-prod-release.apk
